//You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible subsequences of 'STR'.
//A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.
#include <bits/stdc++.h> 
void gen_subsequences(string s,int idx,vector<string>&ans,string curr){
	if(idx==s.size()){
		if(!curr.empty())
	ans.push_back(curr);
	return;}
	gen_subsequences(s,idx+1,ans,curr+s[idx]);
	gen_subsequences(s,idx+1,ans ,curr);
}
vector<string> subsequences(string str){
	vector<string>ans;
	gen_subsequences(str, 0, ans,"");
	return ans;
	// Write your code here
	
}
